version: 0.2

env:
  variables:
    CI: true

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g typescript

  pre_build:
    commands:
      - echo "Pre-build phase..."
      - node --version
      - npm --version
      - export AWS_DEFAULT_REGION=ap-south-1
      - echo "Environment variables loaded"

  build:
    commands:
      - echo "Building the application..."
      - export NODE_ENV=production
      - npm run build
      - echo "Build completed successfully"
      - ls -la dist/
      - test -f dist/index.html

  post_build:
    commands:
      - echo "Post-build phase..."
      - echo "Contents of dist directory:"
      - find dist -type f -name "*.html" -o -name "*.js" -o -name "*.css" | head -10
      - echo "Build artifacts prepared successfully"

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: BuildArtif

cache:
  paths:
    - node_modules/**/*
